### ISSUE TITLE
Implement a find-by-point feature as a separate API endpoint

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/geometry-data-service#7]
Motivated by https://github.com/CSIRO-enviro-informatics/loci-geometry-data-service/issues/3

This issue is for exploring an implementation of find-by-point via a new API. Something like:
`/api/find-by-point?lat=aaa&long=bbb`

This would return matching geometries as a list - in formats like text/turtle, and json also.

**Comment by jyucsiro** [comment]
This is now implemented as
`/search/latlng/<x,y>(/dataset/<dataset_label>)(?crs=<crs_id>)`

dataset and crs are optional. if no CRS, then WGS84/4326 is assumed. see 
http://gds.loci.cat/search/latlng/16615575.46,-4215695.740446/dataset/asgs16_mb?crs=3857

**Comment by dr-shorthair** [comment]
EPSG 4326 is strictly lat-long (y-x). 
The equivalent in lon-lat (x-y) is http://www.opengis.net/def/crs/OGC/1.3/CRS84

**Comment by jyucsiro** [comment]
@dr-shorthair it's whatever this does... https://postgis.net/docs/ST_Point.html

I think it inteprets x-y differently depending on the crs (see the note).

**Comment by dr-shorthair** [comment]
OK - strictly they should not alter the coordinate order. But it looks like they do anyway.
