### ISSUE TITLE
Navigate from geometries to associated Loc-I resources

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/geometry-data-service#8]
Geometries in the data service like http://gds.loci.cat/geometry/asgs16_sa1/21205132002 describe other Loc-I resources in this case 
http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/21205132002. 

Provide a way to navigate from the geometry to the Loc-I resource. 

A use case for https://github.com/CSIRO-enviro-informatics/geometry-data-service/issues/7 i.e searching for geometries by point would be to subsequently find the associated Loc-I resources. With a way to navigate from geometry to resource  https://github.com/CSIRO-enviro-informatics/geometry-data-service/issues/7 should be able to replace (or power) the existing find by point functionality in the integration API

**Comment by dr-shorthair** [comment]
If relationships from geometries --> features need to be persisted, then that would likely require a new property `geox:isGeometryOf owl:inverseOf geo:hasGeometry .`

**Comment by jyucsiro** [comment]
This is now implemented - see http://gds.loci.cat/geometry/asgs16_ra/13?_format=text/turtle&_view=geometryview

Used geox:isGeometryOf to link geoms and features.
